server:
  port: 9527
#prod
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                       #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     #匹配后提供服务的路由地址
#          filters:
#            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/get/**            # 断言，路径相匹配的进行路由
#            - After=2023-03-24T14:15:14.892+08:00[Asia/Shanghai]

#            Cookie Route Predicate需要两个参数，一个是 Cookie name ,一个是正则表达式。
#            路由规则会通过获取对应的 Cookie name 值和正则表达式去匹配，如果匹配上就会执行路由，如果没有匹配上则不执行
#            - Cookie=username,james
#            - Header=X-Request-Id, \d+        # 请求头要有X-Request-Id属性并且值为整数的正则表达式

        - id: payment_routh2 #payment_route     #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
#          filters:
#            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/**             # 断言，路径相匹配的进行路由
#            - After=2023-03-24T14:15:14.892+08:00[Asia/Shanghai]

#            Cookie Route Predicate需要两个参数，一个是 Cookie name ,一个是正则表达式。
#            路由规则会通过获取对应的 Cookie name 值和正则表达式去匹配，如果匹配上就会执行路由，如果没有匹配上则不执行
#            - Cookie=username,james           #cmd测试 curl http://localhost:9527/payment/get/23 --cookie "username=james"
#            请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Header=X-Request-Id, \d+        #curl http://localhost:9527/payment/lb -H "X-Request-Id:123"
            #- Before=2020-02-05T15:10:03.685+08:00[Asia/Shanghai]         # 断言，路径相匹配的进行路由
            #- Between=2020-02-02T17:45:06.206+08:00[Asia/Shanghai],2020-03-25T18:59:06.206+08:00[Asia/Shanghai]
            #- Host=**.uxun.com
#            - Method=GET
#            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/